package com.se_04.enoti.notification;

import java.util.ArrayList;
import java.util.List;

public class NotificationRepository {
    private static NotificationRepository instance;
    private final List<NotificationItem> notifications;

    private NotificationRepository() {
        notifications = new ArrayList<>();
        seedData();
    }

    public static NotificationRepository getInstance() {
        if (instance == null) {
            instance = new NotificationRepository();
        }
        return instance;
    }

    public List<NotificationItem> getNotifications() {
        return notifications;
    }

    private void seedData() {
        notifications.add(new NotificationItem("Cúp điện toàn khu", "01/10/2025 - 02/10/2025", "Bảo trì", "admin", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae est nec nibh sagittis convallis. Nulla pulvinar, nulla quis efficitur tempus, lectus velit elementum mauris, eget sodales purus metus ut tellus. Morbi vitae erat risus. Fusce elementum tellus sed varius tincidunt. Nullam sed maximus dui. Nunc fermentum egestas neque eu placerat. Pellentesque condimentum commodo tincidunt. Praesent aliquam, justo ut imperdiet imperdiet, urna lorem congue lorem, at accumsan nulla metus eu ex. Nam massa risus, eleifend id interdum ac, ullamcorper ut nunc. Aliquam erat volutpat. Duis arcu sem, blandit eu risus et, interdum rutrum urna. Integer rutrum neque urna, non pulvinar nibh imperdiet ac. Quisque ullamcorper suscipit pretium."));
        notifications.add(new NotificationItem("Bảo trì thang máy", "03/10/2025 - 04/10/2025", "Bảo trì", "admin", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae est nec nibh sagittis convallis. Nulla pulvinar, nulla quis efficitur tempus, lectus velit elementum mauris, eget sodales purus metus ut tellus. Morbi vitae erat risus. Fusce elementum tellus sed varius tincidunt. Nullam sed maximus dui. Nunc fermentum egestas neque eu placerat. Pellentesque condimentum commodo tincidunt. Praesent aliquam, justo ut imperdiet imperdiet, urna lorem congue lorem, at accumsan nulla metus eu ex. Nam massa risus, eleifend id interdum ac, ullamcorper ut nunc. Aliquam erat volutpat. Duis arcu sem, blandit eu risus et, interdum rutrum urna. Integer rutrum neque urna, non pulvinar nibh imperdiet ac. Quisque ullamcorper suscipit pretium."));
        notifications.add(new NotificationItem("Họp cư dân", "05/10/2025", "Thông báo", "admin", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae est nec nibh sagittis convallis. Nulla pulvinar, nulla quis efficitur tempus, lectus velit elementum mauris, eget sodales purus metus ut tellus. Morbi vitae erat risus. Fusce elementum tellus sed varius tincidunt. Nullam sed maximus dui. Nunc fermentum egestas neque eu placerat. Pellentesque condimentum commodo tincidunt. Praesent aliquam, justo ut imperdiet imperdiet, urna lorem congue lorem, at accumsan nulla metus eu ex. Nam massa risus, eleifend id interdum ac, ullamcorper ut nunc. Aliquam erat volutpat. Duis arcu sem, blandit eu risus et, interdum rutrum urna. Integer rutrum neque urna, non pulvinar nibh imperdiet ac. Quisque ullamcorper suscipit pretium."));
        notifications.add(new NotificationItem("Thông báo phòng cháy chữa cháy", "07/10/2025", "Thông báo", "admin", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae est nec nibh sagittis convallis. Nulla pulvinar, nulla quis efficitur tempus, lectus velit elementum mauris, eget sodales purus metus ut tellus. Morbi vitae erat risus. Fusce elementum tellus sed varius tincidunt. Nullam sed maximus dui. Nunc fermentum egestas neque eu placerat. Pellentesque condimentum commodo tincidunt. Praesent aliquam, justo ut imperdiet imperdiet, urna lorem congue lorem, at accumsan nulla metus eu ex. Nam massa risus, eleifend id interdum ac, ullamcorper ut nunc. Aliquam erat volutpat. Duis arcu sem, blandit eu risus et, interdum rutrum urna. Integer rutrum neque urna, non pulvinar nibh imperdiet ac. Quisque ullamcorper suscipit pretium."));
        notifications.add(new NotificationItem("Đóng phí dịch vụ tháng 10", "10/10/2025", "Thông báo", "admin", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae est nec nibh sagittis convallis. Nulla pulvinar, nulla quis efficitur tempus, lectus velit elementum mauris, eget sodales purus metus ut tellus. Morbi vitae erat risus. Fusce elementum tellus sed varius tincidunt. Nullam sed maximus dui. Nunc fermentum egestas neque eu placerat. Pellentesque condimentum commodo tincidunt. Praesent aliquam, justo ut imperdiet imperdiet, urna lorem congue lorem, at accumsan nulla metus eu ex. Nam massa risus, eleifend id interdum ac, ullamcorper ut nunc. Aliquam erat volutpat. Duis arcu sem, blandit eu risus et, interdum rutrum urna. Integer rutrum neque urna, non pulvinar nibh imperdiet ac. Quisque ullamcorper suscipit pretium."));
        notifications.add(new NotificationItem("Họp ban quản lý", "15/10/2025", "Tin khẩn", "admin", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae est nec nibh sagittis convallis. Nulla pulvinar, nulla quis efficitur tempus, lectus velit elementum mauris, eget sodales purus metus ut tellus. Morbi vitae erat risus. Fusce elementum tellus sed varius tincidunt. Nullam sed maximus dui. Nunc fermentum egestas neque eu placerat. Pellentesque condimentum commodo tincidunt. Praesent aliquam, justo ut imperdiet imperdiet, urna lorem congue lorem, at accumsan nulla metus eu ex. Nam massa risus, eleifend id interdum ac, ullamcorper ut nunc. Aliquam erat volutpat. Duis arcu sem, blandit eu risus et, interdum rutrum urna. Integer rutrum neque urna, non pulvinar nibh imperdiet ac. Quisque ullamcorper suscipit pretium."));
        notifications.add(new NotificationItem("Cắt nước bảo trì", "20/10/2025", "Bảo trì", "admin", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae est nec nibh sagittis convallis. Nulla pulvinar, nulla quis efficitur tempus, lectus velit elementum mauris, eget sodales purus metus ut tellus. Morbi vitae erat risus. Fusce elementum tellus sed varius tincidunt. Nullam sed maximus dui. Nunc fermentum egestas neque eu placerat. Pellentesque condimentum commodo tincidunt. Praesent aliquam, justo ut imperdiet imperdiet, urna lorem congue lorem, at accumsan nulla metus eu ex. Nam massa risus, eleifend id interdum ac, ullamcorper ut nunc. Aliquam erat volutpat. Duis arcu sem, blandit eu risus et, interdum rutrum urna. Integer rutrum neque urna, non pulvinar nibh imperdiet ac. Quisque ullamcorper suscipit pretium."));
        notifications.add(new NotificationItem("Sự kiện trung thu cho thiếu nhi", "25/10/2025", "Sự kiện", "admin", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae est nec nibh sagittis convallis. Nulla pulvinar, nulla quis efficitur tempus, lectus velit elementum mauris, eget sodales purus metus ut tellus. Morbi vitae erat risus. Fusce elementum tellus sed varius tincidunt. Nullam sed maximus dui. Nunc fermentum egestas neque eu placerat. Pellentesque condimentum commodo tincidunt. Praesent aliquam, justo ut imperdiet imperdiet, urna lorem congue lorem, at accumsan nulla metus eu ex. Nam massa risus, eleifend id interdum ac, ullamcorper ut nunc. Aliquam erat volutpat. Duis arcu sem, blandit eu risus et, interdum rutrum urna. Integer rutrum neque urna, non pulvinar nibh imperdiet ac. Quisque ullamcorper suscipit pretium."));
    }

}
